-- Initial catalog and demo centers.
-- Demo centers are inserted as pending so the admin must verify coordinates
-- before publishing them on the public map.

insert into public.aid_categories (id, label, short_label, accent, surface, sort_order)
values
  ('food', 'Alimentacion', 'Comida', '#F7C948', '#FFF3BF', 10),
  ('health', 'Salud', 'Salud', '#24A7A1', '#D7F8F2', 20),
  ('shelter', 'Refugio', 'Refugio', '#EF6F61', '#FFE2DD', 30),
  ('documents', 'Documentos', 'Docs', '#4E7BD9', '#DFEAFF', 40),
  ('supplies', 'Ropa e insumos', 'Insumos', '#9B6ADB', '#EFE4FF', 50),
  ('transport', 'Transporte', 'Ruta', '#F29E4C', '#FFE8CC', 60),
  ('donations', 'Donaciones', 'Donar', '#5CB85C', '#DFF4DD', 70),
  ('volunteers', 'Voluntariado', 'Voluntarios', '#DB4E7A', '#FFE0EA', 80)
on conflict (id) do update
  set label = excluded.label,
      short_label = excluded.short_label,
      accent = excluded.accent,
      surface = excluded.surface,
      sort_order = excluded.sort_order,
      is_active = true,
      updated_at = now();

insert into public.aid_cities (id, name, department, map_center_lat, map_center_lng, map_zoom)
values
  ('medellin', 'Medellin', 'Antioquia', 6.2442000, -75.5812000, 12),
  ('cartagena', 'Cartagena', 'Bolivar', 10.3910000, -75.4794000, 12),
  ('barranquilla', 'Barranquilla', 'Atlantico', 10.9639000, -74.7964000, 12),
  ('santa-marta', 'Santa Marta', 'Magdalena', 11.2408000, -74.1990000, 12),
  ('bogota', 'Bogota', 'Bogota D.C.', 4.7110000, -74.0721000, 11)
on conflict (id) do update
  set name = excluded.name,
      department = excluded.department,
      map_center_lat = excluded.map_center_lat,
      map_center_lng = excluded.map_center_lng,
      map_zoom = excluded.map_zoom,
      is_active = true,
      updated_at = now();

insert into public.aid_centers (
  slug,
  status,
  name,
  department,
  city,
  city_id,
  neighborhood,
  address,
  formatted_address,
  google_place_id,
  latitude,
  longitude,
  geocode_confidence,
  geocode_location_type,
  geocode_needs_review,
  geocode_query,
  primary_category,
  categories,
  description,
  requirements,
  hours_label,
  public_contact,
  impact_visits,
  impact_supplies_kg,
  impact_families
)
values
  (
    'belen-integral',
    'pending',
    'Centro Integral Belen',
    'Antioquia',
    'Medellin',
    'medellin',
    'Belen',
    'Cra. 76 #32-24, Medellin',
    'Cra. 76 #32-24, Medellin, Belen, Medellin, Antioquia, Colombia',
    'ChIJUxQy570pRI4R02r8cOBsuTI',
    6.2340652,
    -75.5962060,
    'exact',
    'ROOFTOP',
    false,
    'Cra. 76 #32-24, Belen, Medellin, Antioquia, Colombia',
    'food',
    array['food', 'documents', 'supplies'],
    'Entrega de mercados, orientacion documental y kits basicos para familias recien llegadas.',
    'Documento disponible y registro breve en el punto.',
    'Lun, mie y vie · 9:00 a.m. - 3:00 p.m.',
    '+57 300 000 8142',
    146,
    520,
    88
  ),
  (
    'san-javier-salud',
    'pending',
    'Punto Salud San Javier',
    'Antioquia',
    'Medellin',
    'medellin',
    'San Javier',
    'Cl. 44 #95-18, Medellin',
    'Cl. 44 #95-18, Medellin, Antioquia, Colombia',
    null,
    6.2552000,
    -75.6186000,
    'seed',
    null,
    true,
    'Cl. 44 #95-18, San Javier, Medellin, Antioquia, Colombia',
    'health',
    array['health', 'transport'],
    'Jornadas de triage, rutas a atencion primaria y apoyo para desplazamientos medicos.',
    'Llegar 20 minutos antes del cierre.',
    'Mar y jue · 8:00 a.m. - 12:30 p.m.',
    'WhatsApp disponible',
    93,
    120,
    57
  ),
  (
    'casa-puente-prado',
    'pending',
    'Casa Puente Prado',
    'Antioquia',
    'Medellin',
    'medellin',
    'Prado Centro',
    'Cra. 50 #64-32, Medellin',
    'Cra. 50 #64-32, Medellin, Antioquia, Colombia',
    null,
    6.2589000,
    -75.5649000,
    'seed',
    null,
    true,
    'Cra. 50 #64-32, Prado Centro, Medellin, Antioquia, Colombia',
    'shelter',
    array['shelter', 'food', 'volunteers'],
    'Punto de descanso diurno, comida caliente y coordinacion de voluntarios por turnos.',
    'Cupos limitados por orden de llegada.',
    'Todos los dias · 10:00 a.m. - 6:00 p.m.',
    '+57 301 000 2288',
    214,
    780,
    132
  ),
  (
    'red-documental-poblado',
    'pending',
    'Red Documental Poblado',
    'Antioquia',
    'Medellin',
    'medellin',
    'El Poblado',
    'Cl. 10 #43A-22, Medellin',
    'Cl. 10 #43A-22, Medellin, Antioquia, Colombia',
    null,
    6.2092000,
    -75.5677000,
    'seed',
    null,
    true,
    'Cl. 10 #43A-22, El Poblado, Medellin, Antioquia, Colombia',
    'documents',
    array['documents', 'volunteers'],
    'Acompanamiento para citas, orientacion legal y revision de papeles antes de radicar.',
    'Agendar cupo por WhatsApp.',
    'Sab · 9:00 a.m. - 1:00 p.m.',
    'agenda@redsolidaria.co',
    61,
    40,
    39
  ),
  (
    'bodega-solidaria-caribe',
    'pending',
    'Bodega Solidaria Caribe',
    'Antioquia',
    'Medellin',
    'medellin',
    'Caribe',
    'Cra. 64C #75-10, Medellin',
    'Cra. 64C #75-10, Medellin, Antioquia, Colombia',
    null,
    6.2792000,
    -75.5720000,
    'seed',
    null,
    true,
    'Cra. 64C #75-10, Caribe, Medellin, Antioquia, Colombia',
    'donations',
    array['donations', 'supplies', 'transport'],
    'Recepcion y distribucion de donaciones verificadas: ropa, cobijas, higiene y alimentos no perecederos.',
    'Donaciones limpias y separadas por tipo.',
    'Lun a sab · 8:30 a.m. - 5:00 p.m.',
    '+57 304 000 4410',
    78,
    940,
    73
  ),
  (
    'cartagena-manga-solidaria',
    'pending',
    'Punto Solidario Manga',
    'Bolivar',
    'Cartagena',
    'cartagena',
    'Manga',
    'Cra. 18 #29-64, Cartagena',
    'Cra. 18 #29-64, Manga, Cartagena, Bolivar, Colombia',
    null,
    10.4092000,
    -75.5350000,
    'seed',
    null,
    true,
    'Cra. 18 #29-64, Manga, Cartagena, Bolivar, Colombia',
    'food',
    array['food', 'supplies', 'donations'],
    'Punto inicial para coordinar alimentos no perecederos, higiene y donaciones verificadas en Cartagena.',
    'Confirmar disponibilidad antes de llevar donaciones.',
    'Lun, mie y sab · 9:00 a.m. - 2:00 p.m.',
    '+57 305 000 1920',
    42,
    260,
    31
  ),
  (
    'barranquilla-prado-apoyo',
    'pending',
    'Red de Apoyo Prado',
    'Atlantico',
    'Barranquilla',
    'barranquilla',
    'El Prado',
    'Cra. 54 #70-86, Barranquilla',
    'Cra. 54 #70-86, El Prado, Barranquilla, Atlantico, Colombia',
    null,
    10.9898000,
    -74.7892000,
    'seed',
    null,
    true,
    'Cra. 54 #70-86, El Prado, Barranquilla, Atlantico, Colombia',
    'documents',
    array['documents', 'health', 'volunteers'],
    'Orientacion documental, acompanamiento comunitario y rutas a jornadas de salud en Barranquilla.',
    'Llevar documento disponible o soporte de identidad.',
    'Mar y jue · 8:30 a.m. - 1:00 p.m.',
    'apoyo.barranquilla@redsolidaria.co',
    36,
    80,
    24
  ),
  (
    'santa-marta-centro-humanitario',
    'pending',
    'Centro Humanitario Bahia',
    'Magdalena',
    'Santa Marta',
    'santa-marta',
    'Centro Historico',
    'Cl. 17 #3-72, Santa Marta',
    'Cl. 17 #3-72, Centro Historico, Santa Marta, Magdalena, Colombia',
    null,
    11.2426000,
    -74.2111000,
    'seed',
    null,
    true,
    'Cl. 17 #3-72, Centro Historico, Santa Marta, Magdalena, Colombia',
    'food',
    array['food', 'transport', 'volunteers'],
    'Coordinacion de comida caliente, acompanamiento para rutas locales y turnos de voluntariado.',
    'Registro breve en el punto.',
    'Vie y sab · 10:00 a.m. - 4:00 p.m.',
    '+57 302 000 7311',
    29,
    190,
    18
  ),
  (
    'bogota-teusaquillo-documental',
    'pending',
    'Mesa Documental Teusaquillo',
    'Bogota D.C.',
    'Bogota',
    'bogota',
    'Teusaquillo',
    'Cl. 39 #19-45, Bogota',
    'Cl. 39 #19-45, Teusaquillo, Bogota, Bogota D.C., Colombia',
    null,
    4.6351000,
    -74.0719000,
    'seed',
    null,
    true,
    'Cl. 39 #19-45, Teusaquillo, Bogota, Bogota D.C., Colombia',
    'documents',
    array['documents', 'shelter', 'volunteers'],
    'Orientacion para tramites, remisiones a alojamiento temporal y registro de voluntarios en Bogota.',
    'Agendar cupo y llevar soporte de identidad si esta disponible.',
    'Lun a vie · 9:00 a.m. - 5:00 p.m.',
    'bogota@redsolidaria.co',
    67,
    140,
    46
  )
on conflict (slug) do update
  set status = excluded.status,
      name = excluded.name,
      department = excluded.department,
      city = excluded.city,
      city_id = excluded.city_id,
      neighborhood = excluded.neighborhood,
      address = excluded.address,
      formatted_address = excluded.formatted_address,
      google_place_id = excluded.google_place_id,
      latitude = excluded.latitude,
      longitude = excluded.longitude,
      geocode_confidence = excluded.geocode_confidence,
      geocode_location_type = excluded.geocode_location_type,
      geocode_needs_review = excluded.geocode_needs_review,
      geocode_query = excluded.geocode_query,
      primary_category = excluded.primary_category,
      categories = excluded.categories,
      description = excluded.description,
      requirements = excluded.requirements,
      hours_label = excluded.hours_label,
      public_contact = excluded.public_contact,
      impact_visits = excluded.impact_visits,
      impact_supplies_kg = excluded.impact_supplies_kg,
      impact_families = excluded.impact_families,
      updated_at = now();
